const postConstants = {
    FETCH_REQUEST: 'FETCH_POST_REQUEST',
    FETCH_SUCCESS: 'FETCH_POST_SUCCESS',
    FETCH_FAILURE: 'FETCH_POST_FAILURE',
    FETCH_AUTHOR_REQUEST: 'FETCH_POST_AUTHOR_REQUEST',
    FETCH_AUTHOR_SUCCESS: 'FETCH_POST_AUTHOR_SUCCESS',
    FETCH_AUTHOR_FAILURE: 'FETCH_POST_AUTHOR_FAILURE',
};

export default postConstants
